### ISSUE TITLE
The profileInformation array may seem useful but its abstracting meaning

### ISSUE THREAD

**Issue by Razpudding** [gmamar/HomeWork#10]
If you look at it, info.html_url is more readable than info[profileInformation[3]].
I understand it's rally useful for the addFullInfo function but you can get all the info in a different way. If you want to print all the keys of an object and their values you can use this:
```
for (var i in myObject)
{
	console.log("key: " + i + " value: " myObject[i]);
}
```

**Comment by gmamar** [comment]
> If you look at it, info.html_url is more readable than info[profileInformation[3]].

now I understand, when you said in the exam that the array is an **object**
