### ISSUE TITLE
Good job setting up polling

### ISSUE THREAD

**Issue by Razpudding** [gmamar/HomeWork#8]
That's pretty cool, you figured out how to load new info every 60 seconds. You should probably add a check though, to see if a username has been filled in after a minute. Now when you leave the page open without doing anything it tries to get the data for an empty user and that generates an error.

**Comment by gmamar** [comment]
Yeeeeh, you are right.
I edit it to contain if condition to check input field value.
if (srcEntry.value !== null && srcEntry.value !== "")
